# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0 filetype=yaml:

.templates_sha: &template_sha 16f790f93f893394b70d7048fb0e8a981ceaa3c5 # see https://docs.gitlab.com/ee/ci/yaml/#includefile

include:
  - project: 'freedesktop/ci-templates'
    ref: *template_sha
    file: '/templates/debian.yml'
  - project: 'freedesktop/ci-templates'
    ref: *template_sha
    file: '/templates/ci-fairy.yml'
  - template: Security/SAST.gitlab-ci.yml

stages:
  - prep
  - install xorgproto
  - build
  - test
  - deploy

variables:
  FDO_DISTRIBUTION_TAG: '2021-05-30.8'  # change this to rebuild the images
  FDO_UPSTREAM_REPO: 'xorg/lib/libxi'
  FDO_DISTRIBUTION_VERSION: 'stable'
  FDO_DISTRIBUTION_PACKAGES: 'git ca-certificates meson g++ make xutils-dev autoconf automake libtool pkg-config xmlto xorg-sgml-doctools w3m xsltproc libx11-dev libxext-dev libxfixes-dev'

  MESON_BUILDDIR: 'build dir'
  NINJA_ARGS: ''
  MESON_ARGS: ''

#
# Verify that commit messages are as expected
#
check-commits:
  extends:
    - .fdo.ci-fairy
  stage: prep
  script:
    - ci-fairy check-commits --junit-xml=results.xml
  except:
    - master@xorg/proto/xcbproto
  variables:
    GIT_DEPTH: 100
  artifacts:
    reports:
      junit: results.xml
  allow_failure: true

#
# Verify that the merge request has the allow-collaboration checkbox ticked
#
check-merge-request:
  extends:
    - .fdo.ci-fairy
  stage: deploy
  script:
    - ci-fairy check-merge-request --require-allow-collaboration --junit-xml=results.xml
  artifacts:
    when: on_failure
    reports:
      junit: results.xml
  allow_failure: true


#
# Build a container with the given tag and the packages pre-installed.
# This only happens if/when the tag changes, otherwise the existing image is
# re-used.
#
container-prep:
  extends:
    - .fdo.container-build@debian
  stage: prep
  variables:
    GIT_STRATEGY: none

xorgproto-build:
  extends:
    - .fdo.distribution-image@debian
  stage: install xorgproto
  script:
    - export INSTDIR="$PWD/_inst"
    - git clone --depth=1 https://gitlab.freedesktop.org/xorg/proto/xorgproto --branch=xorgproto-2021.4.99.2
    - pushd xorgproto > /dev/null
    - meson -Dprefix="$INSTDIR" _build
    - ninja -j${FDO_CI_CONCURRENT:-4} -C _build install
    - popd > /dev/null
  variables:
  artifacts:
    paths:
      - _inst

build:
  extends:
    - .fdo.distribution-image@debian
  stage: build
  script:
    - export INSTDIR="$PWD/_inst"
    - export PKG_CONFIG_PATH=$(find $INSTDIR/ -name '*.pc' -printf "%h:")
    - autoreconf -fi
    - mkdir build
    - pushd build > /dev/null
    - ../configure
    - make all -j${FDO_CI_CONCURRENT:-4}
    - popd > /dev/null
